-- Add UG/PG program-level scope to marks lock and introduce attendance lock.
-- Safe to re-run: uses IF EXISTS / IF NOT EXISTS guards.
-- Backward compat: existing marks_entry_lock rows get program_level = 'ALL'
-- which continues to block both UG and PG marks entry.

-- 1. Extend marks_entry_lock with program_level.
ALTER TABLE marks_entry_lock
    ADD COLUMN IF NOT EXISTS program_level VARCHAR(10) NOT NULL DEFAULT 'ALL';

-- Drop the old unique key (name is auto-generated by Postgres; try common names).
ALTER TABLE marks_entry_lock DROP CONSTRAINT IF EXISTS marks_entry_lock_slot_year_semester_type_component_type_key;
ALTER TABLE marks_entry_lock DROP CONSTRAINT IF EXISTS marks_entry_lock_unique;

-- Add the new 4-column unique key.
ALTER TABLE marks_entry_lock ADD CONSTRAINT marks_entry_lock_unique
    UNIQUE (slot_year, semester_type, component_type, program_level);

-- 2. Attendance lock table (parallel to marks_entry_lock, no component_type).
CREATE TABLE IF NOT EXISTS attendance_entry_lock (
    id SERIAL PRIMARY KEY,
    slot_year VARCHAR(20) NOT NULL,
    semester_type VARCHAR(10) NOT NULL,
    program_level VARCHAR(10) NOT NULL,   -- 'UG', 'PG', 'ALL'
    is_locked BOOLEAN DEFAULT FALSE,
    locked_by INTEGER,
    locked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (slot_year, semester_type, program_level),
    FOREIGN KEY (locked_by) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_attendance_lock_semester
    ON attendance_entry_lock(slot_year, semester_type);
